[project]
name = "tts-python-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "hume>=0.7.8",
  "python-dotenv>=1.0.1",
]
